### ISSUE TITLE
Ver manejo de los atributos y campos null en los productos

### ISSUE THREAD

**Issue by JuaniElias** [julianmino/mi-vinoteca#13]
Los numericupdown no permiten NULL para ser mapeados de los atributos que van vacios.
Como resolvemos? Podemos instalar WPF que agrega mas controles a los win form o modificar el nativo, u otra forma que se les ocurra

**Comment by julianmino** [comment]
Una posibilidad que se me ocurre es usar un TextBox en vez de NumericUpDown, y configurarlo para que si el usuario intenta escribir algo que no sea un número, haga una concatenación de un espacio vacío (""). Así te aseguras que sólo va a quedar un número dentro del TextBox (o vacío, y puedas pasarlo como null).
Otra que se me ocurre es que, cuando quieras hacer el alta de un determinado producto (por ejemplo, un Vino) y se abra el formulario de ABMProductos, hagas un switch que desactive los componentes que no corresponden a dicho producto, en este caso Vino (por ejemplo, IBU).

Pregunta: Si implementamos WPF, ¿se modificaría la estructura del código y/o del diseño de la parte de Desktop?

**Comment by JuaniElias** [comment]
> Pregunta: Si implementamos WPF, ¿se modificaría la estructura del código y/o del diseño de la parte de Desktop?

Se aplicaria solo sobre uno de los formularios pero habria que hacerlo todo devuelta (en este caso el ABMProductos)
El switch ya esta hecho, el problema es cuando se quiere mapear un NULL a un campo numerico, se podrian hacer los switch para cada caso pero no se si quedaria tan bien

**Comment by julianmino** [comment]
Entonces no lo veo conveniente... Considerando los tiempos y la complejidad, creo que es mejor buscar una solución sin nuevas implementaciones (quizás una alternativa más simple). Después me pongo a verlo, o podemos verlo juntos.
