### ISSUE TITLE
La singularizacion de las tablas con EF no nos sirve más

### ISSUE THREAD

**Issue by JuaniElias** [julianmino/mi-vinoteca#18]
La tabla "Productores" queda en la DAL como "Productore".

¿Pluralizo todo o solo corrijo productores (va a haber que corregirlo siempre que se actualice la DAL)?

Tema serio

**Comment by julianmino** [comment]
Si bien lo más probable es que no tengamos que actualizar de nuevo la DAL, creo que es mejor pluralizar todo, para evitar estos inconvenientes si nos surge la necesidad de actualizar.

**Comment by JuaniElias** [comment]
Agree, ya lo estoy cambiando
