### ISSUE TITLE
Traduccion de los textos de todas las paginas al español

### ISSUE THREAD

**Issue by JuaniElias** [julianmino/mi-vinoteca#3]
Me refiero a poner en español los campos de los login y los textos del header por ejemplo.
Ya se que esto lo podia preguntar por wasap pero queria probar como funcionan los issues.

**Comment by julianmino** [comment]
Esta genial que lo preguntes por aca, asi tenemos un seguimiento más formal del proyecto.
Si, sería conveniente que todos los textos estén en español. ¿Querés hacerlo?

**Comment by JuaniElias** [comment]
Si ahora lo hago Juli
