### ISSUE TITLE
Base de Datos

### ISSUE THREAD

**Issue by tmalgarin** [julianmino/mi-vinoteca#4]
@julianmino como va la base de datos? No sé si está en algún lugar por acá o no. Pero ya llegue a la parte de sign up y necesito la BD para seguir. Si necesitas ayuda para armarla, aunque sea logistica, pega el chiflido

**Comment by julianmino** [comment]
Hoy la termino. Mientras tanto, podés ir pensando el formato que va a tener el formulario de un pedido (un buen comienzo sería plasmarlo en alguna herramienta de diseño de interfaz)

**Comment by tmalgarin** [comment]
Podriamos usar la que hicimos de la biblioteca, es casi lo mismo me parece a mi.

**Comment by julianmino** [comment]
Abro nuevo hilo aparte para responder.
En cuanto a la base de datos, te pudiste fijar si está subida en el repositorio? Cualquier cosa avisame.

**Comment by JuaniElias** [comment]
DB up & running
